// Education Mode Types

export type EducationMode = 'student' | 'teacher' | 'learner' | 'researcher' | 'default';

export type ProvenanceCategory =
  | 'canonical_education'
  | 'solver_verified'
  | 'llm_generated'
  | 'user_input'
  | 'historical_case'
  | 'live_data';

export interface ProvenanceBadge {
  label: string;
  icon: string;
  color: string;
  description: string;
  requiresVerification: boolean;
}

export const PROVENANCE_BADGES: Record<ProvenanceCategory, ProvenanceBadge> = {
  canonical_education: {
    label: 'Canonical',
    icon: '📚',
    color: 'emerald',
    description: 'Sourced from canonical game theory education content',
    requiresVerification: true,
  },
  solver_verified: {
    label: 'Solver',
    icon: '✓',
    color: 'blue',
    description: 'Verified by deterministic solver',
    requiresVerification: true,
  },
  llm_generated: {
    label: 'AI',
    icon: '🤖',
    color: 'amber',
    description: 'Generated by AI model — not verified',
    requiresVerification: false,
  },
  user_input: {
    label: 'User',
    icon: '👤',
    color: 'purple',
    description: 'Provided by user',
    requiresVerification: false,
  },
  historical_case: {
    label: 'Case',
    icon: '📖',
    color: 'orange',
    description: 'Historical case study',
    requiresVerification: false,
  },
  live_data: {
    label: 'Live',
    icon: '📡',
    color: 'cyan',
    description: 'Live data source',
    requiresVerification: false,
  },
};

export interface ProvenanceMetadata {
  category: ProvenanceCategory;
  verifiedBy: string;
  sources: string[];
  confidence: number;
  stepByStepReasoning?: string[];
  timestamp?: number;
}

export function createProvenanceMetadata(
  category: ProvenanceCategory,
  options: {
    verifiedBy?: string;
    sources?: string[];
    confidence?: number;
    stepByStepReasoning?: string[];
  } = {}
): ProvenanceMetadata {
  return {
    category,
    verifiedBy: options.verifiedBy ?? 'unknown',
    sources: options.sources ?? [],
    confidence: options.confidence ?? 0,
    stepByStepReasoning: options.stepByStepReasoning,
    timestamp: Date.now(),
  };
}
