import React from 'react'

const TermsOfService: React.FC = () => (
  <div className="min-h-screen bg-slate-900 p-6">
    <div className="max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold text-white mb-6">Terms of Service</h1>
      <div className="bg-slate-800 rounded-xl border border-slate-700 p-8 space-y-4 text-slate-300">
        <p className="text-sm text-slate-400">Last updated: July 5, 2026</p>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using the Strategic Intelligence Platform ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">2. AI-Generated Content Disclaimer</h2>
          <p>All strategic analysis, forecasts, and recommendations provided by the Service are generated by artificial intelligence for research and educational purposes. Outputs may contain errors, biases, or incomplete information. You must independently verify all outputs before making any decisions. The Service is not a substitute for professional advice.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">3. No Warranties</h2>
          <p>The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not guarantee the accuracy, reliability, or completeness of any analysis or forecast.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">4. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, arising from your use of the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">5. Acceptable Use</h2>
          <p>You agree not to: (a) use the Service for unlawful purposes; (b) attempt to reverse engineer, decompile, or disassemble any part of the Service; (c) abuse rate limits or attempt to circumvent authentication; (d) use AI-generated outputs without independent verification for real-world decision-making.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">6. Payment and Subscriptions</h2>
          <p>Payment functionality is currently in development. Free tier access is available with rate limits. Paid tiers will be introduced with full billing terms when payment integration is activated.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">7. Changes to Terms</h2>
          <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">8. Contact</h2>
          <p>For questions about these Terms, contact us at <a href="mailto:support@strategicintelligence.com" className="text-purple-400 hover:text-purple-300">support@strategicintelligence.com</a>.</p>
        </section>
      </div>
    </div>
  </div>
)

export default TermsOfService
