-- NON-APPLIED DRAFT: identity_and_review RLS remediation
-- Generated by scripts/build-rls-policy-draft.mjs.
-- Do not place this file under supabase/migrations or apply it to hosted Supabase
-- until owner classification, current hosted policy inspection, and local pgTAP
-- test helpers are complete.
--
-- Proof boundary:
-- - This is a draft, not an executed migration.
-- - Supabase service_role keys can bypass RLS server-side; never expose them to clients.
-- - Public reads are intentionally not included for analysis_runs, users,
--   human_reviews, asset_storage, or schema_failures in this draft.

-- Harden helper used by RLS role predicates.
create or replace function public.get_user_role()
returns text
security definer
set search_path = public
language sql
stable
as $$
  select u.role
  from public.users u
  where u.auth_id = (select auth.uid())::uuid
  limit 1
$$;

-- Remove legacy broad policies for the first remediation batch.
drop policy if exists read_anon_runs on public.analysis_runs;
drop policy if exists read_public_runs on public.analysis_runs;
drop policy if exists read_runs on public.analysis_runs;
drop policy if exists public_read_completed_runs on public.analysis_runs;
drop policy if exists mvp_insert_anon_runs on public.analysis_runs;
drop policy if exists insert_service_role_runs on public.analysis_runs;
drop policy if exists reviewer_read_analysis_runs on public.analysis_runs;
drop policy if exists reviewer_update_analysis_runs on public.analysis_runs;
drop policy if exists admin_access_analysis_runs on public.analysis_runs;

drop policy if exists read_human_reviews on public.human_reviews;
drop policy if exists reviewer_read_human_reviews on public.human_reviews;
drop policy if exists reviewer_write_human_reviews on public.human_reviews;
drop policy if exists admin_access_human_reviews on public.human_reviews;

drop policy if exists read_users_public on public.users;
drop policy if exists read_users on public.users;

drop policy if exists read_asset_storage on public.asset_storage;
drop policy if exists read_schema_failures on public.schema_failures;

-- Remove prior draft policy names as well, so the final approved migration can be idempotent.
drop policy if exists identity_review_owner_read_analysis_runs on public.analysis_runs;
drop policy if exists identity_review_owner_insert_analysis_runs on public.analysis_runs;
drop policy if exists identity_review_reviewer_read_analysis_runs on public.analysis_runs;
drop policy if exists identity_review_reviewer_update_analysis_runs on public.analysis_runs;
drop policy if exists identity_review_admin_all_analysis_runs on public.analysis_runs;

drop policy if exists identity_review_owner_read_human_reviews on public.human_reviews;
drop policy if exists identity_review_reviewer_read_human_reviews on public.human_reviews;
drop policy if exists identity_review_reviewer_update_human_reviews on public.human_reviews;
drop policy if exists identity_review_admin_all_human_reviews on public.human_reviews;

drop policy if exists identity_review_owner_read_users on public.users;
drop policy if exists identity_review_admin_all_users on public.users;

drop policy if exists identity_review_owner_read_asset_storage on public.asset_storage;
drop policy if exists identity_review_reviewer_read_asset_storage on public.asset_storage;
drop policy if exists identity_review_admin_all_asset_storage on public.asset_storage;

drop policy if exists identity_review_admin_read_schema_failures on public.schema_failures;

alter table public.analysis_runs enable row level security;
alter table public.human_reviews enable row level security;
alter table public.users enable row level security;
alter table public.asset_storage enable row level security;
alter table public.schema_failures enable row level security;

-- analysis_runs: owner, reviewer queue, and admin.
create policy identity_review_owner_read_analysis_runs
  on public.analysis_runs
  for select
  to authenticated
  using (user_id = (select auth.uid()));

create policy identity_review_owner_insert_analysis_runs
  on public.analysis_runs
  for insert
  to authenticated
  with check (user_id = (select auth.uid()));

create policy identity_review_reviewer_read_analysis_runs
  on public.analysis_runs
  for select
  to authenticated
  using (
    public.get_user_role() = 'reviewer'
    and status in ('needs_review', 'under_review')
  );

create policy identity_review_reviewer_update_analysis_runs
  on public.analysis_runs
  for update
  to authenticated
  using (
    public.get_user_role() = 'reviewer'
    and status in ('needs_review', 'under_review')
  )
  with check (
    public.get_user_role() = 'reviewer'
    and status in ('needs_review', 'under_review', 'approved', 'rejected')
  );

create policy identity_review_admin_all_analysis_runs
  on public.analysis_runs
  for all
  to authenticated
  using (public.get_user_role() = 'admin')
  with check (public.get_user_role() = 'admin');

-- human_reviews: owner through analysis_run, assigned/queue reviewer, and admin.
create policy identity_review_owner_read_human_reviews
  on public.human_reviews
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.analysis_runs ar
      where ar.id = human_reviews.analysis_run_id
        and ar.user_id = (select auth.uid())
    )
  );

create policy identity_review_reviewer_read_human_reviews
  on public.human_reviews
  for select
  to authenticated
  using (
    public.get_user_role() = 'reviewer'
    and (
      reviewer_id = (select auth.uid())::text
      or exists (
        select 1
        from public.analysis_runs ar
        where ar.id = human_reviews.analysis_run_id
          and ar.status in ('needs_review', 'under_review')
      )
    )
  );

create policy identity_review_reviewer_update_human_reviews
  on public.human_reviews
  for update
  to authenticated
  using (
    public.get_user_role() = 'reviewer'
    and reviewer_id = (select auth.uid())::text
  )
  with check (
    public.get_user_role() = 'reviewer'
    and reviewer_id = (select auth.uid())::text
  );

create policy identity_review_admin_all_human_reviews
  on public.human_reviews
  for all
  to authenticated
  using (public.get_user_role() = 'admin')
  with check (public.get_user_role() = 'admin');

-- users: own row and admin only.
create policy identity_review_owner_read_users
  on public.users
  for select
  to authenticated
  using (auth_id = (select auth.uid()));

create policy identity_review_admin_all_users
  on public.users
  for all
  to authenticated
  using (public.get_user_role() = 'admin')
  with check (public.get_user_role() = 'admin');

-- asset_storage: owner through analysis_run, approved review queue, and admin.
create policy identity_review_owner_read_asset_storage
  on public.asset_storage
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.analysis_runs ar
      where ar.id = asset_storage.analysis_run_id
        and ar.user_id = (select auth.uid())
    )
  );

create policy identity_review_reviewer_read_asset_storage
  on public.asset_storage
  for select
  to authenticated
  using (
    public.get_user_role() = 'reviewer'
    and exists (
      select 1
      from public.analysis_runs ar
      where ar.id = asset_storage.analysis_run_id
        and ar.status in ('needs_review', 'under_review')
    )
  );

create policy identity_review_admin_all_asset_storage
  on public.asset_storage
  for all
  to authenticated
  using (public.get_user_role() = 'admin')
  with check (public.get_user_role() = 'admin');

-- schema_failures: no owner path exists in current migrations.
-- Draft default: admin-only direct reads; service-role jobs can manage server-side.
-- Owner alternative: add analysis_run_id/user_id and mirror owner/reviewer policies.
create policy identity_review_admin_read_schema_failures
  on public.schema_failures
  for select
  to authenticated
  using (public.get_user_role() = 'admin');
