-- RLS acceptance test template for identity_and_review
-- Generated by scripts/build-rls-acceptance-test-plan.mjs.
-- Proof boundary: template only. Do not treat this as passing RLS proof until
-- owner-approved policies are migrated and this file is run with supabase test db.
--
-- Primary docs basis:
-- - supabase test db [path] runs pgTAP tests locally or, with approval, on a linked project.
-- - Supabase RLS tests should authenticate seeded personas and assert both positive and negative access cases.

begin;

-- TODO after approval:
-- 1. Create this as supabase/tests/identity_and_review_rls.test.sql.
-- 2. Add or import Supabase docs-compatible test helpers, for example:
--    tests.create_supabase_user(...)
--    tests.authenticate_as(...)
--    tests.authenticate_as_service_role()
--    tests.clear_authentication()
-- 3. Seed owner, unrelated, reviewer, admin, and service-role setup rows.
-- 4. Run: supabase test db supabase/tests/identity_and_review_rls.test.sql --local
-- 5. After owner approval, run: supabase test db supabase/tests/identity_and_review_rls.test.sql --linked

select plan(27);

-- analysis_runs.anon_select_denied: results_eq count from analysis_runs visible to anon is 0; expected zero private rows visible.
-- analysis_runs.unrelated_authenticated_select_denied: results_eq count from analysis_runs for unrelated authenticated user is 0; expected zero owner/private rows visible.
-- analysis_runs.owner_path_allowed: results_eq count from analysis_runs for owner is 1; expected owner-visible row count is 1.
-- analysis_runs.reviewer_path_limited: results_eq reviewer-visible rows from analysis_runs match approved review seed only; expected reviewer sees only approved review-queue or assigned rows.
-- analysis_runs.service_role_path_allowed: lives_ok service-role operation for analysis_runs; expected service role can perform trusted setup/edge-function operation.
-- analysis_runs.anon_insert_denied: throws_ok anon insert into analysis_runs with SQLSTATE 42501; expected insert rejected by RLS.
-- analysis_runs.unrelated_authenticated_write_denied: throws_ok unrelated authenticated write to analysis_runs with SQLSTATE 42501; expected write rejected unless row owner or approved reviewer/service role.
-- human_reviews.anon_select_denied: results_eq count from human_reviews visible to anon is 0; expected zero private rows visible.
-- human_reviews.unrelated_authenticated_select_denied: results_eq count from human_reviews for unrelated authenticated user is 0; expected zero owner/private rows visible.
-- human_reviews.owner_path_allowed: results_eq count from human_reviews for owner is 1; expected owner-visible row count is 1.
-- human_reviews.reviewer_path_limited: results_eq reviewer-visible rows from human_reviews match approved review seed only; expected reviewer sees only approved review-queue or assigned rows.
-- human_reviews.service_role_path_allowed: lives_ok service-role operation for human_reviews; expected service role can perform trusted setup/edge-function operation.
-- users.anon_select_denied: results_eq count from users visible to anon is 0; expected zero private rows visible.
-- users.unrelated_authenticated_select_denied: results_eq count from users for unrelated authenticated user is 0; expected zero owner/private rows visible.
-- users.owner_path_allowed: results_eq count from users for owner is 1; expected owner-visible row count is 1.
-- users.reviewer_path_limited: results_eq reviewer-visible rows from users match approved review seed only; expected reviewer sees only approved review-queue or assigned rows.
-- users.service_role_path_allowed: lives_ok service-role operation for users; expected service role can perform trusted setup/edge-function operation.
-- asset_storage.anon_select_denied: results_eq count from asset_storage visible to anon is 0; expected zero private rows visible.
-- asset_storage.unrelated_authenticated_select_denied: results_eq count from asset_storage for unrelated authenticated user is 0; expected zero owner/private rows visible.
-- asset_storage.owner_path_allowed: results_eq count from asset_storage for owner is 1; expected owner-visible row count is 1.
-- asset_storage.reviewer_path_limited: results_eq reviewer-visible rows from asset_storage match approved review seed only; expected reviewer sees only approved review-queue or assigned rows.
-- asset_storage.service_role_path_allowed: lives_ok service-role operation for asset_storage; expected service role can perform trusted setup/edge-function operation.
-- schema_failures.anon_select_denied: results_eq count from schema_failures visible to anon is 0; expected zero private rows visible.
-- schema_failures.unrelated_authenticated_select_denied: results_eq count from schema_failures for unrelated authenticated user is 0; expected zero owner/private rows visible.
-- schema_failures.owner_path_allowed: schema prerequisite before owner read test for schema_failures; expected blocked until owner path exists.
-- schema_failures.reviewer_path_limited: results_eq reviewer-visible rows from schema_failures match approved review seed only; expected reviewer sees only approved review-queue or assigned rows.
-- schema_failures.service_role_path_allowed: lives_ok service-role operation for schema_failures; expected service role can perform trusted setup/edge-function operation.

-- analysis_runs
-- Owner path: public.analysis_runs.user_id = auth.uid()
-- Reviewer path: status in ('needs_review', 'under_review') and get_user_role() in ('reviewer', 'admin')
-- Service-role path: auth.role() = 'service_role'
-- Minimum seed: owner private run, unrelated private run, review-queue run, completed public-exception candidate
-- Public exception default: only if an owner-approved published/redacted status is introduced; completed alone is not enough for enterprise-private rows
-- Source findings: supabase/migrations/20250304_0001_create_users_table.sql:54, supabase/migrations/20250826_0001_init.sql:43, supabase/migrations/20250902184556_0002_write_policies.sql:9, supabase/migrations/20250902184557_0003_mvp_anon_insert.sql:10
-- TODO after owner approval: replace this placeholder with pgTAP results_eq/throws_ok/lives_ok assertions for analysis_runs.

-- human_reviews
-- Owner path: review owner through analysis_runs.user_id, plus reviewer_id when the actor is the assigned reviewer
-- Reviewer path: get_user_role() in ('reviewer', 'admin') and reviewer_id::uuid = auth.uid() for writes
-- Service-role path: auth.role() = 'service_role'
-- Minimum seed: review linked to owner run, review linked to unrelated run, assigned reviewer, unassigned reviewer
-- Public exception default: none by default
-- Source findings: supabase/migrations/20250304_0001_create_users_table.sql:62, supabase/migrations/20250904_0010_extend_analysis_runs_for_audience.sql:99
-- TODO after owner approval: replace this placeholder with pgTAP results_eq/throws_ok/lives_ok assertions for human_reviews.

-- users
-- Owner path: public.users.auth_id = auth.uid()
-- Reviewer path: security-definer role lookup only; direct reviewer reads need owner approval and column minimization
-- Service-role path: auth.role() = 'service_role'
-- Minimum seed: owner user row, unrelated user row, reviewer user row, admin user row
-- Public exception default: none by default
-- Source findings: supabase/migrations/20250304_0001_create_users_table.sql:58, supabase/migrations/20250904_0010_extend_analysis_runs_for_audience.sql:105
-- TODO after owner approval: replace this placeholder with pgTAP results_eq/throws_ok/lives_ok assertions for users.

-- asset_storage
-- Owner path: asset owner through analysis_runs.user_id
-- Reviewer path: reviewer/admin only for assets linked to review-queue runs if owner-approved
-- Service-role path: auth.role() = 'service_role'
-- Minimum seed: asset linked to owner run, asset linked to unrelated run, asset linked to review-queue run
-- Public exception default: only via explicit published/redacted asset workflow
-- Source findings: supabase/migrations/20250904_0010_extend_analysis_runs_for_audience.sql:102
-- TODO after owner approval: replace this placeholder with pgTAP results_eq/throws_ok/lives_ok assertions for asset_storage.

-- schema_failures
-- Owner path: no durable owner column in current migration; add analysis_run_id/user_id or restrict to admin/service-role only
-- Reviewer path: admin/reviewer read only if failure metadata is redacted and owner-approved
-- Service-role path: auth.role() = 'service_role'
-- Minimum seed: private validation failure with request_id, owner-linked failure after schema update, unrelated failure
-- Public exception default: none by default
-- Source findings: supabase/migrations/20250904_0010_extend_analysis_runs_for_audience.sql:128
-- TODO after owner approval: replace this placeholder with pgTAP results_eq/throws_ok/lives_ok assertions for schema_failures.

select * from finish();
rollback;
